// source: authzed/api/v0/namespace_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var validate_validate_pb = require('../../../validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
var authzed_api_v0_core_pb = require('../../../authzed/api/v0/core_pb.js');
goog.object.extend(proto, authzed_api_v0_core_pb);
var authzed_api_v0_namespace_pb = require('../../../authzed/api/v0/namespace_pb.js');
goog.object.extend(proto, authzed_api_v0_namespace_pb);
goog.exportSymbol('proto.authzed.api.v0.ReadConfigRequest', null, global);
goog.exportSymbol('proto.authzed.api.v0.ReadConfigResponse', null, global);
goog.exportSymbol('proto.authzed.api.v0.WriteConfigRequest', null, global);
goog.exportSymbol('proto.authzed.api.v0.WriteConfigResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.authzed.api.v0.ReadConfigRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.authzed.api.v0.ReadConfigRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.authzed.api.v0.ReadConfigRequest.displayName = 'proto.authzed.api.v0.ReadConfigRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.authzed.api.v0.ReadConfigResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.authzed.api.v0.ReadConfigResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.authzed.api.v0.ReadConfigResponse.displayName = 'proto.authzed.api.v0.ReadConfigResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.authzed.api.v0.WriteConfigRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.authzed.api.v0.WriteConfigRequest.repeatedFields_, null);
};
goog.inherits(proto.authzed.api.v0.WriteConfigRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.authzed.api.v0.WriteConfigRequest.displayName = 'proto.authzed.api.v0.WriteConfigRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.authzed.api.v0.WriteConfigResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.authzed.api.v0.WriteConfigResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.authzed.api.v0.WriteConfigResponse.displayName = 'proto.authzed.api.v0.WriteConfigResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.authzed.api.v0.ReadConfigRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.authzed.api.v0.ReadConfigRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.authzed.api.v0.ReadConfigRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.authzed.api.v0.ReadConfigRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespace: jspb.Message.getFieldWithDefault(msg, 1, ""),
    atRevision: (f = msg.getAtRevision()) && authzed_api_v0_core_pb.Zookie.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.authzed.api.v0.ReadConfigRequest}
 */
proto.authzed.api.v0.ReadConfigRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.authzed.api.v0.ReadConfigRequest;
  return proto.authzed.api.v0.ReadConfigRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.authzed.api.v0.ReadConfigRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.authzed.api.v0.ReadConfigRequest}
 */
proto.authzed.api.v0.ReadConfigRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    case 2:
      var value = new authzed_api_v0_core_pb.Zookie;
      reader.readMessage(value,authzed_api_v0_core_pb.Zookie.deserializeBinaryFromReader);
      msg.setAtRevision(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.authzed.api.v0.ReadConfigRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.authzed.api.v0.ReadConfigRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.authzed.api.v0.ReadConfigRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.authzed.api.v0.ReadConfigRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAtRevision();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      authzed_api_v0_core_pb.Zookie.serializeBinaryToWriter
    );
  }
};


/**
 * optional string namespace = 1;
 * @return {string}
 */
proto.authzed.api.v0.ReadConfigRequest.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.authzed.api.v0.ReadConfigRequest} returns this
 */
proto.authzed.api.v0.ReadConfigRequest.prototype.setNamespace = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Zookie at_revision = 2;
 * @return {?proto.authzed.api.v0.Zookie}
 */
proto.authzed.api.v0.ReadConfigRequest.prototype.getAtRevision = function() {
  return /** @type{?proto.authzed.api.v0.Zookie} */ (
    jspb.Message.getWrapperField(this, authzed_api_v0_core_pb.Zookie, 2));
};


/**
 * @param {?proto.authzed.api.v0.Zookie|undefined} value
 * @return {!proto.authzed.api.v0.ReadConfigRequest} returns this
*/
proto.authzed.api.v0.ReadConfigRequest.prototype.setAtRevision = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.authzed.api.v0.ReadConfigRequest} returns this
 */
proto.authzed.api.v0.ReadConfigRequest.prototype.clearAtRevision = function() {
  return this.setAtRevision(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.authzed.api.v0.ReadConfigRequest.prototype.hasAtRevision = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.authzed.api.v0.ReadConfigResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.authzed.api.v0.ReadConfigResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.authzed.api.v0.ReadConfigResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespace: jspb.Message.getFieldWithDefault(msg, 1, ""),
    config: (f = msg.getConfig()) && authzed_api_v0_namespace_pb.NamespaceDefinition.toObject(includeInstance, f),
    revision: (f = msg.getRevision()) && authzed_api_v0_core_pb.Zookie.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.authzed.api.v0.ReadConfigResponse}
 */
proto.authzed.api.v0.ReadConfigResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.authzed.api.v0.ReadConfigResponse;
  return proto.authzed.api.v0.ReadConfigResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.authzed.api.v0.ReadConfigResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.authzed.api.v0.ReadConfigResponse}
 */
proto.authzed.api.v0.ReadConfigResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    case 2:
      var value = new authzed_api_v0_namespace_pb.NamespaceDefinition;
      reader.readMessage(value,authzed_api_v0_namespace_pb.NamespaceDefinition.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    case 4:
      var value = new authzed_api_v0_core_pb.Zookie;
      reader.readMessage(value,authzed_api_v0_core_pb.Zookie.deserializeBinaryFromReader);
      msg.setRevision(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.authzed.api.v0.ReadConfigResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.authzed.api.v0.ReadConfigResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.authzed.api.v0.ReadConfigResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      authzed_api_v0_namespace_pb.NamespaceDefinition.serializeBinaryToWriter
    );
  }
  f = message.getRevision();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      authzed_api_v0_core_pb.Zookie.serializeBinaryToWriter
    );
  }
};


/**
 * optional string namespace = 1;
 * @return {string}
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.authzed.api.v0.ReadConfigResponse} returns this
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.setNamespace = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional NamespaceDefinition config = 2;
 * @return {?proto.authzed.api.v0.NamespaceDefinition}
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.getConfig = function() {
  return /** @type{?proto.authzed.api.v0.NamespaceDefinition} */ (
    jspb.Message.getWrapperField(this, authzed_api_v0_namespace_pb.NamespaceDefinition, 2));
};


/**
 * @param {?proto.authzed.api.v0.NamespaceDefinition|undefined} value
 * @return {!proto.authzed.api.v0.ReadConfigResponse} returns this
*/
proto.authzed.api.v0.ReadConfigResponse.prototype.setConfig = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.authzed.api.v0.ReadConfigResponse} returns this
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.clearConfig = function() {
  return this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Zookie revision = 4;
 * @return {?proto.authzed.api.v0.Zookie}
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.getRevision = function() {
  return /** @type{?proto.authzed.api.v0.Zookie} */ (
    jspb.Message.getWrapperField(this, authzed_api_v0_core_pb.Zookie, 4));
};


/**
 * @param {?proto.authzed.api.v0.Zookie|undefined} value
 * @return {!proto.authzed.api.v0.ReadConfigResponse} returns this
*/
proto.authzed.api.v0.ReadConfigResponse.prototype.setRevision = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.authzed.api.v0.ReadConfigResponse} returns this
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.clearRevision = function() {
  return this.setRevision(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.authzed.api.v0.ReadConfigResponse.prototype.hasRevision = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.authzed.api.v0.WriteConfigRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.authzed.api.v0.WriteConfigRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.authzed.api.v0.WriteConfigRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.authzed.api.v0.WriteConfigRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.authzed.api.v0.WriteConfigRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    configsList: jspb.Message.toObjectList(msg.getConfigsList(),
    authzed_api_v0_namespace_pb.NamespaceDefinition.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.authzed.api.v0.WriteConfigRequest}
 */
proto.authzed.api.v0.WriteConfigRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.authzed.api.v0.WriteConfigRequest;
  return proto.authzed.api.v0.WriteConfigRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.authzed.api.v0.WriteConfigRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.authzed.api.v0.WriteConfigRequest}
 */
proto.authzed.api.v0.WriteConfigRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new authzed_api_v0_namespace_pb.NamespaceDefinition;
      reader.readMessage(value,authzed_api_v0_namespace_pb.NamespaceDefinition.deserializeBinaryFromReader);
      msg.addConfigs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.authzed.api.v0.WriteConfigRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.authzed.api.v0.WriteConfigRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.authzed.api.v0.WriteConfigRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.authzed.api.v0.WriteConfigRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConfigsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      authzed_api_v0_namespace_pb.NamespaceDefinition.serializeBinaryToWriter
    );
  }
};


/**
 * repeated NamespaceDefinition configs = 2;
 * @return {!Array<!proto.authzed.api.v0.NamespaceDefinition>}
 */
proto.authzed.api.v0.WriteConfigRequest.prototype.getConfigsList = function() {
  return /** @type{!Array<!proto.authzed.api.v0.NamespaceDefinition>} */ (
    jspb.Message.getRepeatedWrapperField(this, authzed_api_v0_namespace_pb.NamespaceDefinition, 2));
};


/**
 * @param {!Array<!proto.authzed.api.v0.NamespaceDefinition>} value
 * @return {!proto.authzed.api.v0.WriteConfigRequest} returns this
*/
proto.authzed.api.v0.WriteConfigRequest.prototype.setConfigsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.authzed.api.v0.NamespaceDefinition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.authzed.api.v0.NamespaceDefinition}
 */
proto.authzed.api.v0.WriteConfigRequest.prototype.addConfigs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.authzed.api.v0.NamespaceDefinition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.authzed.api.v0.WriteConfigRequest} returns this
 */
proto.authzed.api.v0.WriteConfigRequest.prototype.clearConfigsList = function() {
  return this.setConfigsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.authzed.api.v0.WriteConfigResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.authzed.api.v0.WriteConfigResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.authzed.api.v0.WriteConfigResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.authzed.api.v0.WriteConfigResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    revision: (f = msg.getRevision()) && authzed_api_v0_core_pb.Zookie.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.authzed.api.v0.WriteConfigResponse}
 */
proto.authzed.api.v0.WriteConfigResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.authzed.api.v0.WriteConfigResponse;
  return proto.authzed.api.v0.WriteConfigResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.authzed.api.v0.WriteConfigResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.authzed.api.v0.WriteConfigResponse}
 */
proto.authzed.api.v0.WriteConfigResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new authzed_api_v0_core_pb.Zookie;
      reader.readMessage(value,authzed_api_v0_core_pb.Zookie.deserializeBinaryFromReader);
      msg.setRevision(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.authzed.api.v0.WriteConfigResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.authzed.api.v0.WriteConfigResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.authzed.api.v0.WriteConfigResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.authzed.api.v0.WriteConfigResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRevision();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      authzed_api_v0_core_pb.Zookie.serializeBinaryToWriter
    );
  }
};


/**
 * optional Zookie revision = 1;
 * @return {?proto.authzed.api.v0.Zookie}
 */
proto.authzed.api.v0.WriteConfigResponse.prototype.getRevision = function() {
  return /** @type{?proto.authzed.api.v0.Zookie} */ (
    jspb.Message.getWrapperField(this, authzed_api_v0_core_pb.Zookie, 1));
};


/**
 * @param {?proto.authzed.api.v0.Zookie|undefined} value
 * @return {!proto.authzed.api.v0.WriteConfigResponse} returns this
*/
proto.authzed.api.v0.WriteConfigResponse.prototype.setRevision = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.authzed.api.v0.WriteConfigResponse} returns this
 */
proto.authzed.api.v0.WriteConfigResponse.prototype.clearRevision = function() {
  return this.setRevision(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.authzed.api.v0.WriteConfigResponse.prototype.hasRevision = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.authzed.api.v0);
