---
# yamllint disable rule:line-length
name: "Publish to NPM"
on:  # yamllint disable-line rule:truthy
  release:
    types:
      - "published"
jobs:
  publish:
    name: Publish to NPM
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent
          working-directory: ./
      - run: yarn test
      - uses: battila7/get-version-action@v2
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ steps.get_version.outputs.version }}
          access: public
  # NOTE: this publishes an alternate version that doesn't depend on protobuf-ts/runtime
  publish-js-client:
    name: Publish JS client to NPM
    needs: build-js-client
    runs-on: ubuntu-latest
    steps:
      - name: Download js client build
        uses: actions/download-artifact@v4
        with:
          name: js-client-18
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent
          working-directory: ./
      - uses: battila7/get-version-action@v2
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ steps.get_version.outputs.version }}
          access: public
