---
name: "Test"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  paths-filter:
    runs-on: "depot-ubuntu-24.04-small"
    outputs:
      codechange: "${{ steps.code-filter.outputs.codechange }}"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "dorny/paths-filter@v3"
        id: "code-filter"
        with:
          filters: |
            codechange:
              - src/**
              - .github/workflows/authzed-node.yaml
              - package.json
              - js-dist/package.json
              - buf.gen.yaml
  test:
    name: "Test"
    runs-on: "depot-ubuntu-24.04-small"
    strategy:
      matrix:
        node-version: [22, 24, 26]
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    steps:
      - uses: "actions/checkout@v6"
      - uses: "authzed/action-spicedb@v1"
        with:
          version: "latest"
      - uses: "actions/setup-node@v6"
        with:
          node-version: ${{ matrix.node-version }}
      - uses: "pnpm/action-setup@v6"
        with:
          cache: true
          run_install: true
      - name: Run tests
        run: "CI=true pnpm only-run-tests"
  build-js-client:
    name: "Build and Test JS client"
    runs-on: "depot-ubuntu-24.04-small"
    strategy:
      matrix:
        node-version: [22, 24, 26]
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: "authzed/action-spicedb@v1"
        with:
          version: "latest"
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: "pnpm/action-setup@v6"
        with:
          cache: true
          run_install: true
      - name: Run build
        run: pnpm build-js-client
        working-directory: ./
      - name: Run tests
        run: CI=true pnpm only-run-tests
        working-directory: ./js-dist
      - uses: actions/upload-artifact@v6
        with:
          name: js-client-${{ matrix.node-version }}
          path: |
            js-dist/**
            !js-dist/node_modules/**
